/* 
 * Arrays de objetos con la piezas de juego.
    * nombre: nombre de la pieza
    * imagen: figura asociada
    * up,down,left,rigth : indican mediante true o false si son accesibles por ese borde
 */
module.exports=[
    {
       nombre:"blockSup",
       imagen:"T1.png",
       up:false,
       down:true,
       left:false,
       rigth:false
    },
    {
       nombre:"blockLeft",
       imagen:"T2.png",
       up:false,
       down:false,
       left:false,
       rigth:true
    },
    {
       nombre:"blockdown",
       imagen:"T4.png",
       up:true,
       down:false,
       left:false,
       rigth:false
    },
    {
       nombre:"blockRigth",
       imagen:"T8.png",
       up:false,
       down:false,
       left:true,
       rigth:false
    },
    {
       nombre:"GiroLeftUp",
       imagen:"T12.png",
       up:true,
       down:false,
       left:true,
       rigth:false
    },
    {
       nombre:"GiroDownRigth",
       imagen:"T3.png",
       up:false,
       down:true,
       left:false,
       rigth:true
    },
    {
       nombre:"GiroUpRigth",
       imagen:"T6.png",
       up:true,
       down:false,
       left:false,
       rigth:true
    },
    {
       nombre:"GiroLeftDown",
       imagen:"T9.png",
       up:false,
       down:true,
       left:true,
       rigth:false
    },
    {
       nombre:"CruceUp",
       imagen:"T14.png",
       up:true,
       down:false,
       left:true,
       rigth:true
    },
    {
       nombre:"CruceDown",
       imagen:"T11.png",
       up:false,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"CruceLeft",
       imagen:"T13.png",
       up:true,
       down:true,
       left:true,
       rigth:false
    },
    {
       nombre:"CruceRigth",
       imagen:"T7.png",
       up:true,
       down:true,
       left:false,
       rigth:true
    },
    {
       nombre:"rectaUpDown",
       imagen:"T5.png",
       up:true,
       down:true,
       left:false,
       rigth:false
    },
    {
       nombre:"rectaLeftRigth",
       imagen:"T10.png",
       up:false,
       down:false,
       left:true,
       rigth:true
    },
    {
       nombre:"Cruce",
       imagen:"T15.png",
       up:true,
       down:true,
       left:true,
       rigth:true
    }
];

