/* 
 * Arrays de objetos con la piezas de juego.
    * nombre: nombre de la pieza
    * imagen: figura asociada
    * up,down,left,rigth : indican mediante true o false si son accesibles por ese borde
    * piezas:
    * de 0 a 14 -->piezas de juego
    * 15 --> interrogacion
    * 16 --> oro sin descubrir
    * 17 --> no oro sin descubir
    * 18 --> salida
    * 19 --> oro descubierto
    * 20 --> no oro descubierto
 */
module.exports=[
    {
       nombre:"blockSup",
       imagen:"T1.png",
       propietario:null,
       up:false,
       down:true,
       left:false,
       rigth:false
    },
    {
       nombre:"blockLeft",
       imagen:"T2.png",
       propietario:null,
       up:false,
       down:false,
       left:false,
       rigth:true
    },
    {
       nombre:"blockdown",
       imagen:"T4.png",
       propietario:null,
       up:true,
       down:false,
       left:false,
       rigth:false
    },
    {
       nombre:"blockRigth",
       imagen:"T8.png",
       propietario:null,
       up:false,
       down:false,
       left:true,
       rigth:false
    },
    {
       nombre:"GiroLeftUp",
       imagen:"T12.png",
       propietario:null,
       up:true,
       down:false,
       left:true,
       rigth:false
    },
    {
       nombre:"GiroDownRigth",
       imagen:"T3.png",
       propietario:null,
       up:false,
       down:true,
       left:false,
       rigth:true
    },
    {
       nombre:"GiroUpRigth",
       imagen:"T6.png",
       propietario:null,
       up:true,
       down:false,
       left:false,
       rigth:true
    },
    {
       nombre:"GiroLeftDown",
       imagen:"T9.png",
       propietario:null,
       up:false,
       down:true,
       left:true,
       rigth:false
    },
    {
       nombre:"CruceUp",
       imagen:"T14.png",
       propietario:null,
       up:true,
       down:false,
       left:true,
       rigth:true
    },
    {
       nombre:"CruceDown",
       imagen:"T11.png",
       propietario:null,
       up:false,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"CruceLeft",
       imagen:"T13.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:false
    },
    {
       nombre:"CruceRigth",
       imagen:"T7.png",
       propietario:null,
       up:true,
       down:true,
       left:false,
       rigth:true
    },
    {
       nombre:"rectaUpDown",
       imagen:"T5.png",
       propietario:null,
       up:true,
       down:true,
       left:false,
       rigth:false
    },
    {
       nombre:"rectaLeftRigth",
       imagen:"T10.png",
       propietario:null,
       up:false,
       down:false,
       left:true,
       rigth:true
    },
    {
       nombre:"Cruce",
       imagen:"T15.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"DNK",
       imagen:"DNK.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"Gold",
       imagen:"DNK.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"NoGold",
       imagen:"DNK.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"Start",
       imagen:"T15.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"VisGold",
       imagen:"Gold.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
    {
       nombre:"VisNoGold",
       imagen:"NoGold.png",
       propietario:null,
       up:true,
       down:true,
       left:true,
       rigth:true
    },
];

