-- MySQL Script generated by MySQL Workbench
-- 12/16/16 00:00:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema saboteur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saboteur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saboteur` DEFAULT CHARACTER SET utf8 ;
USE `saboteur` ;

-- -----------------------------------------------------
-- Table `saboteur`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saboteur`.`Usuarios` (
  `ID_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID del usuario para su busqueda rapida',
  `Nick` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(8) NOT NULL,
  `Fecha_Nac` VARCHAR(10) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Imagen` LONGBLOB NULL,
  PRIMARY KEY (`ID_usuario`),
  UNIQUE INDEX `ID_UNIQUE` (`ID_usuario` ASC),
  UNIQUE INDEX `Nick_UNIQUE` (`Nick` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`Partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saboteur`.`Partidas` (
  `ID_Partida` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Estado_Partida` INT UNSIGNED NOT NULL DEFAULT 0,
  `Creador` INT UNSIGNED NOT NULL,
  `Num_Jugadores` INT UNSIGNED NOT NULL DEFAULT 0,
  `Num_Max_Jugadores` INT UNSIGNED NOT NULL,
  `Turno` INT UNSIGNED NOT NULL DEFAULT 0,
  `Ganador` VARCHAR(30) NULL,
  `Num_Turnos` INT UNSIGNED NOT NULL,
  `Fecha_Creacion` VARCHAR(10) NOT NULL,
  `Turno_juego` INT(2) UNSIGNED NULL DEFAULT '1',
  PRIMARY KEY (`ID_Partida`),
  UNIQUE INDEX `ID_UNIQUE` (`ID_Partida` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  CONSTRAINT `ID_Creador`
    FOREIGN KEY (`Creador`)
    REFERENCES `saboteur`.`Usuarios` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`Asignacion_Partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saboteur`.`Asignacion_Partidas` (
  `ID_Partida` INT UNSIGNED NOT NULL,
  `ID_Usuario` INT UNSIGNED NOT NULL,
  `Tipo_Jugador` VARCHAR(1) NULL,
  `Pos_Turno` INT(2) UNSIGNED NULL,
  `mano1` INT(2) NULL,
  `mano2` INT(2) NULL,
  `mano3` INT(2) NULL,
  `mano4` INT(2) NULL,
  `mano5` INT(2) NULL,
  `mano6` INT(2) NULL,
  PRIMARY KEY (`ID_Partida`, `ID_Usuario`),
  INDEX `ID` (`ID_Usuario` ASC),
  CONSTRAINT `ID_partida`
    FOREIGN KEY (`ID_Partida`)
    REFERENCES `saboteur`.`Partidas` (`ID_Partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_usuario`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `saboteur`.`Usuarios` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saboteur`.`Piezas_partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saboteur`.`Piezas_partida` (
  `ID_Pieza` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_Partida` INT UNSIGNED NOT NULL,
  `Pos_Pieza` INT(2) UNSIGNED NOT NULL,
  `Tipo_Pieza` INT(2) UNSIGNED NOT NULL,
  `Propietario` VARCHAR(20) NOT NULL,
  INDEX `INDEX` (`ID_Partida` ASC),
  PRIMARY KEY (`ID_Pieza`),
  CONSTRAINT `ID_Piezas_Partida`
    FOREIGN KEY (`ID_Partida`)
    REFERENCES `saboteur`.`Partidas` (`ID_Partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
